### ISSUE TITLE
Add responsive layout to Sidebar

### ISSUE THREAD

**Issue by MelanieZirkel** [DeFi-Analytics/DeFi-Analytics#10]
The layout must adjust to the browser size.
Maybe realizable with menu-button.

**Comment by DanielZirkel** [comment]
In mobile version (menu on the top) the menu should be collapsed after selection.

**Comment by DanielZirkel** [comment]
Symbol for menu (3 lines) should not have a yellow border after clicking on it

**Comment by MelanieZirkel** [comment]
> 
> 
> Symbol for menu (3 lines) should not have a yellow border after clicking on it

Done

**Comment by MelanieZirkel** [comment]
> 
> 
> In mobile version (menu on the top) the menu should be collapsed after selection.

Done

> 
> 
> In mobile version (menu on the top) the menu should be collapsed after selection.

Done
