### ISSUE TITLE
DEX coinprices charts: use solid lines 

### ISSUE THREAD

**Issue by nippur72** [DeFi-Analytics/DeFi-Analytics#114]
the DEX coinprices chart ("absolute prices") use red coloured dashed and dotted lines which are not very readable. Can we have solid lines of different colors?

**Comment by DanielZirkel** [comment]
Thanks for feedback. You are right. The original idea was using the same color than in the "Relative price deviation".

I try to switch to new colors and solid lines and will post the first draft here as a screenshot.

**Comment by DanielZirkel** [comment]
Really hard to find a good solution.
The DEX-price has now a solid black line and the other ones a thinner, colored solid line.
![image](https://user-images.githubusercontent.com/68841661/119382711-b6b62600-bcc2-11eb-80d2-fa7e39464621.png)

**Comment by DanielZirkel** [comment]
Another option, which I find better:
The DEX-price as a thick solid line with same color as in "Relative price deviation".
Bittrex and Coingecko as thinner solid line in black and grey.
![image](https://user-images.githubusercontent.com/68841661/119397074-f8040100-bcd5-11eb-822b-fe38db615c45.png)

**Comment by nippur72** [comment]
thanks, it's much better :+1:
