### ISSUE TITLE
Distinguish Masternodes

### ISSUE THREAD

**Issue by DanielZirkel** [DeFi-Analytics/DeFi-Analytics#23]
With the API 
https://poolapi.cakedefi.com/nodes?order=status&orderBy=DESC
you can get the masternodes hosted by Cake.
In future it would be nice to distinguish between Cake Defichain Masternodes and other.

**Comment by SurmannJonas** [comment]
Plus a transparent overview (pie chart et cetera) to which parties the Masternodes belong (Cake, External, External Exchanges, et cetera)

**Comment by DanielZirkel** [comment]
@SurmannJonas In principal that would be very nice. But I see a problem in finding out who is the owner of a masternode.
In case of Cake there is an API getting the addresses of their masternodes. If we find analogue API or information, than I can also mark these "special" masternodes

**Comment by DanielZirkel** [comment]
Absolute and relative representation added, will be released with next dashboard version.
