### ISSUE TITLE
Sidebar must be selected, when accessing a content directly via URL

### ISSUE THREAD

**Issue by MelanieZirkel** [DeFi-Analytics/DeFi-Analytics#24]
When a content is accessed via URL, the sidebar must be selected correctly. Example:
http://127.0.0.1:8050/blockchain?entry=coin

**Comment by DanielZirkel** [comment]
The old timestamp information of the clicked menu entry is saved in a hidden-Div.
With this information the direct URL access works as wanted.
But choosing a graphic collapses now all not needed menus. The behavior is like direct access via URL, not "surfing on Dashboard"

**Comment by DanielZirkel** [comment]
There are 3 cases to be handled:
- clicking on menu for collapse or unfold
- initial load of page via URL input
- clicking on graphic in other menu => URL change (here nothing should be done)
