### ISSUE TITLE
Wrong highlighting of Links

### ISSUE THREAD

**Issue by DanielZirkel** [DeFi-Analytics/DeFi-Analytics#42]
The usage of a background image for Links in the menu results in a wrong highlighting (mouse-over) for "normal" links
![image](https://user-images.githubusercontent.com/68841661/112380700-fe7ff780-8ce9-11eb-9c27-d7bd277efb4a.png)
Maybe an own class for the menu links must be defined.

**Comment by MelanieZirkel** [comment]
Changed classname of the links of the sidebar. Working now

**Comment by DanielZirkel** [comment]
All links are now working (see also issue #43)
