### ISSUE TITLE
Add remaining submenues and links to sidebar

### ISSUE THREAD

**Issue by MelanieZirkel** [DeFi-Analytics/DeFi-Analytics#7]
The remaining submenus and links have to be added (see attached file)

- submenus
- links
- callbacks

![20210302_224529](https://user-images.githubusercontent.com/79751399/109719640-3a231800-7ba9-11eb-8406-37b2bba16171.jpg)

**Comment by MelanieZirkel** [comment]
@DanielZirkel: What about the CoinsLocked link? why is it in brackets?

**Comment by DanielZirkel** [comment]
@MelanieZirkel The CoinsLocked evaluation is not implemented on the old dashboard and must be developed first.
I have created issue #11

**Comment by DanielZirkel** [comment]
@MelanieZirkel a small finding: collapse of Token-menu is not working

**Comment by DanielZirkel** [comment]
Following menu and entries are needed:

- General - Overview (URL: http://127.0.0.1:8050/general?entry=overview)
- Social Media - Twitter (URL: http://127.0.0.1:8050/social?entry=twitter)

**Comment by DanielZirkel** [comment]
Also renaming of files and classes from SocialMedia to Community
